export const categories = [
    { "title": "Erin Moriarty calls out Megyn Kelly, denies plastic surgery", "category": "Entertainment" },
  { "title": "'The Boys' actress Erin Moriarty fires back at Megyn Kelly over allegations she is 'obsessed' with plastic sur", "category": "Entertainment" },
  { "title": "'The Boys' star Erin Moriarty claps back at Megyn Kelly after plastic surgery accusations", "category": "Entertainment" },
  { "title": "Dakota Johnson Shouts Out Taylor Swift in 'Saturday Night Live' Monologue: 'Most Powerful Person in America'", "category": "Entertainment" },
  { "title": "How Dakota Johnson Honored Taylor Swift on SNL", "category": "Entertainment" },
  { "title": "Jacob Elordi talks about filming ‘Saltburn,’ confirms ‘Lilo & Stitch’ Elvis is the best Elvis on ‘Saturday Night Live’", "category": "Entertainment" },
  { "title": "Dakota Johnson jokes Taylor Swift is ‘most powerful person in America’, not Trump", "category": "Entertainment" },
  { "title": "Forget the PlayStation Portal — this $7 app fixed my biggest problem with remote play", "category": "Video Games" },
  { "title": "PlayStation Portal stutter woes solved as user finds crucial fix", "category": "Video Games" },
  { "title": "Best PlayStation Portal games 2024 - top titles for dreamy remote play", "category": "Video Games" },
  { "title": "PlayStation Portal Stuttering is Caused By Refresh Rate Issues Streaming Over Remote Play", "category": "Video Games" },
  { "title": "A New Co-op Zombie Game is Coming Out Next Month", "category": "Video Games" },
  { "title": "Welcome to ParadiZe - Official Story Trailer", "category": "Video Games" },
  { "title": "Preorders Now Available for 'Welcome To ParadiZe' [Trailer]", "category": "Video Games" },
  { "title": "Welcome to ParadiZe shares story trailer and preorder bonuses ahead of February release", "category": "Video Games" },
  { "title": "Why one particular diet is found to be the best year after year", "category": "Health" },
  { "title": "Why the Mediterranean diet is found to be best year after year", "category": "Health" },
  { "title": "The Mediterranean Diet Is Healthiest Again, Says New Report. Here are the 8 Easiest Med Diet Recipes to Try.", "category": "Health" },
  { "title": "The Mediterranean Diet Has Ranked #1 For Seven Years In a Row—What Makes It So Effective?", "category": "Health" },
  { "title": "The S&P 500 Just Hit an All-Time High. Here's 1 Artificial Intelligence (AI) Stock to Buy and Hold Hand Over Fist.", "category": "Business" },
  { "title": "These 3 \"Magnificent Seven\" Stocks Hit All-Time Highs on the Same Day. Here's the Better Buy in 2024.", "category": "Business" },
  { "title": "Nvidia Stock, Other AI Stocks' Sales To Soar", "category": "Business" },
  { "title": "5 Best Artificial Intelligence Stocks to Buy Now, According to Analysts – January 2024 - TipRanks.com", "category": "Business" },
  { "title": "Tesla Next-Generation $25,000 'Model 2' Will Face Low-Priced U.S. Rival", "category": "Automotive" },
  { "title": "Musk: Tesla's Texas engineers will sleep on production line", "category": "Automotive" },
  { "title": "Elon Musk warns Tesla workers of grueling production ramp-up for its mass-market EV", "category": "Automotive" },
  { "title": "Exclusive: Tesla plans to build new electric vehicles in mid-2025", "category": "Automotive" },
  { "title": "Each Zodiac Sign's Weekly Horoscope For January 29 - February 4, 2024", "category": "Astrology" },
  { "title": "Weekly Horoscope Readings for Every Zodiac Sign: 1/28–2/3/24", "category": "Astrology" },
  { "title": "Horoscope for the Week of January 28, 2024, Weekly Horoscope", "category": "Astrology" },
  { "title": "Weekly Horoscope: Check Astrological prediction from 29th January to 4th February", "category": "Astrology" },
  { "title": "New Palworld mod adds essential feature, and it's already blasting off", "category": "Video Games" },
  { "title": "Palworld New Mod Enables Ray Tracing, Increases Ambient Occlusion and Shadow Quality", "category": "Video Games" },
  { "title": "Palworld ray tracing mod makes your pals shiny, but there's a catch", "category": "Video Games" },
  { "title": "Aquaman 2 Is First DCEU Movie Since Original To Pass Huge Global Box Office Milestone", "category": "Movies" },
  { "title": "AQUAMAN AND THE LOST KINGDOM Is The First DCEU Movie Since AQUAMAN To Pass $400 Million Worldwide AQUAMAN AND THE LOST KINGDOM Is The First DCEU Movie Since AQUAMAN To Pass $400 Million Worldwide", "category": "Movies" },
  { "title": "Aquaman and the Lost Kingdom, Ferrari, and every new movie to watch at home this weekend", "category": "Movies" },
  { "title": "New Movies on Streaming: 'Aquaman and the Lost Kingdom' + More", "category": "Movies" },
  { "title": "MSI's new RTX 4080 Super is like a Founders Edition, but faster", "category": "Technology" },
  { "title": "This underrated AMD GPU beats the RTX 4070 Ti Super", "category": "Technology" },
  { "title": "ASUS ROG GeForce RTX 4070 Ti SUPER Gaming STRIX OC review", "category": "Technology" },
  { "title": "Nvidia RTX 4080 Super and 4070 Ti Super go on sale early – but new benchmark leak might make you think twice about buying the latter GPU", "category": "Technology" },
  { "title": "Woman rips screen off her Samsung smart TV while filming unboxing", "category": "Technology" },
  { "title": "Couple mistakenly rip 'screen' off their new smart TV while filming unboxing", "category": "Technology" },
  { "title": "Woman Accidentally Peels Screen off TV — Not Protective Film", "category": "Technology" },
  { "title": "Mavs' Luka Doncic available vs. Kings after record outing", "category": "Sports" },
  { "title": "After historic night, Luka Doncic will be associated with 73 forever", "category": "Sports" },
  { "title": "Hardaway credits Hawks for getting his career on the right path - The Official Home of the Dallas Mavericks", "category": "Sports" },
  { "title": "Luka Doncic scores 73 points in Friday night game", "category": "Sports" },
  { "title": "House GOP unveils Mayorkas impeachment articles", "category": "Politics" },
  { "title": "House Republicans unveil articles of impeachment against DHS Sec. Mayorkas", "category": "Politics" },
  { "title": "Republicans unveil impeachment articles against head of homeland security", "category": "Politics" },
  { "title": "House Republicans release articles of impeachment against Homeland Security Secretary Mayorkas", "category": "Politics" },
  { "title": "Palworld accuser adjusted models to better support Pokemon plagiarism claims", "category": "Video Games" },
  { "title": "Palworld vs. Pokémon Comparison: Just How Similar Are the Designs?", "category": "Video Games" },
  { "title": "Palword’s ‘Pokédex’ has way fewer Pals, and I love it", "category": "Video Games" },
  { "title": "The Pokémon Company Issues Statement On Palworld Copyright Controversy", "category": "Video Games" },
  { "title": "iOS 18 Potentially 'Biggest' Software Update in iPhone's History", "category": "Technology" },
  { "title": "Apple thinks iOS 18 might be the 'biggest' iOS update ever", "category": "Technology" },
  { "title": "Apple boosts plans to bring generative AI to iPhones", "category": "Technology" },
  { "title": "Insider says iOS 18 'Crystal' will be one of the biggest updates in Apple's history", "category": "Technology" },
  { "title": "X-Men Just Officially Replaced a Founding Member, Permanently Rewriting 40 Years of Marvel History", "category": "Comics" },
  { "title": "Marvel rolls back the clock nearly 40 years by bringing back the Beast of 1985", "category": "Comics" },
  { "title": "The X-Men Are Trying to Solve Their Beast Problem in the Wildest Way", "category": "Comics" },
  { "title": "X-Force #48 review", "category": "Comics" },
  { "title": "What's behind the tech industry's mass layoffs in 2024?", "category": "Business" },
  { "title": "Tech layoffs balloon in January as Wall Street rally lifts Alphabet, Meta, Microsoft to records", "category": "Business" },
  { "title": "More than 24,000 tech workers have been laid off this week alone", "category": "Business" },
  { "title": "Layoffs in 2024: List of companies that announced job cuts so far this year", "category": "Business" },
  { "title": "The Boys' Erin Moriarty Slams Plastic Surgery Claims, Leaves Instagram", "category": "Entertainment" }
]